### ISSUE TITLE
Background downloading data

### ISSUE THREAD

**Issue by ghost** [barmstrong/bitcoin-android#16]
Suggestion:

Would it be possible to implement an option to allow the app to collect the blocks in the background, to minimize the waiting time before the chain is up to date? This way you don't get a long wait time if you have not launched the app in a week or so and then want to make a payment.

**Comment by barmstrong** [comment]
Hi kveras, great idea.  This has been added in version 1.1 (update available from the Android Market).  Hope it helps!
