### ISSUE TITLE
Unable to access .apk

### ISSUE THREAD

**Issue by cyanitol** [barmstrong/bitcoin-android#18]
Unable to access from android market or find an APK to install.  Android 2.2.1

**Comment by barmstrong** [comment]
Added the apk files under the Downloads section if you want to manually install it here: https://github.com/barmstrong/bitcoin-android/archives/master

(there is one for production and one for testnet)

Or here is a manual link to the android page: https://market.android.com/details?id=com.bitcoinandroid&feature=search_result

Look for the coins icon if searching from your phone.  It may not be on the first page of results.  Thanks!

**Comment by cyanitol** [comment]
Thank you exactly what was needed.  Was eventually going to compile it myself once I downloaded all the dependencies for the sdk and such.
