### ISSUE TITLE
Show % complete on block chain download

### ISSUE THREAD

**Issue by brandoniles** [barmstrong/bitcoin-android#21]

**Comment by thallium205** [comment]
Isn't it already keeping track in blockChainDownloadSuccessful?  ->

while (true) {
                double pct = 100.0 - (100.0 \* (current / (double) max));
                System.out.println(String.format("Chain download %d%% done", (int) pct));
.
.
.

**Comment by barmstrong** [comment]
Added this in 1.1 release.
