### ISSUE TITLE
Blockchain never finishes updating on Motorola Droid running 2.2

### ISSUE THREAD

**Issue by rexdart** [barmstrong/bitcoin-android#25]
I really want to like this app, but unfortunately it never seems to complete the blockchain download on my Motorola Droid running Android 2.2.  The Droid is connected on a 3mb Wifi connection and is not rooted.  I also tried connecting over 3G.  The circle in the upper right corner just continues to spin and I never receive any transactions that are sent to the phone, although the transactions are confirmed in the Windows client I am sending from.  I re-installed several times with the same result.  Please fix this as I am looking forward to having a real bitcoin wallet on my mobile!  Thanks

**Comment by NoahZThacker** [comment]
I had this same problem.  It just takes a ridiculous amount of time to download the blockchain for some phones.  Hours.  Just be patient and it will eventually work.  If you've reinstalled the app then you won't be able to receive any transactions from the previous install, though.  I guess they are currently working on adding something that tells you the percent download.

**Comment by rexdart** [comment]
I let it run for over 24 hours and it never completed.  I wouldn't mind waiting but the problem is it seems to be a heavy battery drain in the meantime. So my phone is dying on me in the middle of the day which isn't really workable.

**Comment by barmstrong** [comment]
Hi, version 1.1 in the Android Market now shows better status updates as it is downloading, so you may want to try updating the app.  Hopefully it gives more insight into the progress it's making.

**Comment by rexdart** [comment]
UPDATE: After upgrading to version 1.1, the block chain finished downloading and synching in about 20 hours and I have successfully received a payment.  Looks good thanks!
