### ISSUE TITLE
Transaction not completing.

### ISSUE THREAD

**Issue by AndroidScanDroid** [barmstrong/bitcoin-android#26]
Hi, I've sent a micro transaction to test the app but it never sent, I suspect it's the amount I used: .001BTC

But here's the buggy part, as the transaction is still pending, it won't let me send on to any other address for .01 as it tell's me my payment is exceeding what I have, when my balance is fine.

Any suggestions, also it would be cool if people could bother you guys for support outside of github.

Nice project otherwise tho.

**Comment by barmstrong** [comment]
Hello and thanks!  Version 1.1 now supports 8 decimals places.  Try updating from the Android Market and see if this fixes it.
