### ISSUE TITLE
Lost coin after phone reset

### ISSUE THREAD

**Issue by sneakin** [barmstrong/bitcoin-android#36]
I had to reset my phone. I reinstalled Bitcoin [Android], synced the blickchain, and have zero for a balance. Before the reset I had one coin my phone. Seems like the wallet backup was not used. How do I retrieve the backup and reclaim that coin?

**Comment by barmstrong** [comment]
Hmm, yep if you uninstall it I believe it deletes your wallet from the cloud.  Apologies for the trouble on that!  We are working on a better solution going forward that I'll be sure to post more about here.
