### ISSUE TITLE
Switch to allow testnet

### ISSUE THREAD

**Issue by gary-rowe** [barmstrong/bitcoin-android#7]
Had an issue from a user asking how the client could be switched to use Testnet. Couldn't find any instructions.

See http://forum.bitcoin.org/index.php?topic=26718.msg335884#msg335884

**Comment by brandoniles** [comment]
There's currently no way to use testnet without changing a flag in the code and recompiling.

**Comment by brandoniles** [comment]
Since testnet is mostly intended for developers, we'll likely create a separate testnet release for the market instead of adding extra options to the main application.

**Comment by gary-rowe** [comment]
Sounds like the right approach. Perhaps trial the latest features in Testnet under beta, and then push them out to release on prodnet once developers have kicked the tyres.
